kotlin {
    android {
        compileSdk = libs.versions.android.sdk.compile.get().toInteger()
        minSdk = libs.versions.android.sdk.min.get().toInteger()

        withHostTestBuilder {}
    }

    jvmToolchain(libs.versions.jvmtarget.get().toInteger())

    sourceSets {
        getByName("androidHostTest") {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}
