plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.jibru.kostra.resources")
}

apply from: "$rootProject.projectDir/../build-native-lib.gradle"
apply from: "$rootProject.projectDir/../build-ktlint.gradle"

kotlin {
    createNativeTarget(delegate).with {
        binaries {
            executable {
                entryPoint = 'main'
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kostra.common)
            }
        }
        nativeMain {
        }
    }
}


kostra {
    KClassName = "app.native.N"
    strictMode = false
    resourceDirs.add(file("../shared/src/commonMain/resources"))
    androidResources {
        resourceDirs.add(file("../shared/src/commonMain/resources_strings"))
    }
}
