pluginManagement {
    repositories {
        mavenLocal()
        maven { url "https://maven.pkg.jetbrains.space/public/p/compose/dev" }
        gradlePluginPortal()
        google()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("../gradle/libs.versions.toml"))
        }
    }
    repositories {
        mavenLocal()
        maven { url "https://maven.pkg.jetbrains.space/public/p/compose/dev" }
        google()
        mavenCentral()
    }
}


rootProject.name = "kostra-sample-app"
includeBuild("../") {
    dependencySubstitution {
        //libs ^ doesn't exist here yet
        substitute module('com.jibru.kostra:kostra-common') using project(':kostra-common')
        substitute module('com.jibru.kostra:kostra-compose') using project(':kostra-compose')
        substitute module('com.jibru.kostra.resources:com.jibru.kostra.resources.gradle.plugin') using project(':kostra-gradle-plugin')
    }
}
include("shared")
include("shared-lib1")
include("shared-lib2")
include("appJvmConsole")
include("appJvmDesktop")
include("appNativeConsole")
include("appAndroid")
