import com.jibru.kostra.plugin.ResourcesDefaults

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.android.kotlin.multiplatform.library")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.jibru.kostra.resources")
}

apply from: "$rootProject.projectDir/../build-ktlint.gradle"
apply from: "$rootProject.projectDir/../build-android-lib.gradle"

kotlin {
    jvm()

    android {
        namespace = "com.sample.lib1"
    }
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kostra.common)
                implementation(libs.kostra.compose)
                implementation(libs.bundles.jetbrains.compose.app)
            }
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

kostra {
    modulePrefix = "Lib1"
    resourcesDefaults.value([ResourcesDefaults.ComposeGetters])
    KClassName = "com.sample.lib1.KLib1"
    androidResources {
        resourceDirs.add(file("src/commonMain/resources_strings"))
    }
}
