plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.jibru.kostra.resources")
}

apply from: "$rootProject.projectDir/../build-ktlint.gradle"

kotlin {
    jvm()

    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kostra.common)
            }
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

kostra {
    modulePrefix = "Lib2"
    KClassName = "com.sample.lib2.KLib2"
    androidResources {
        resourceDirs.add(file("src/commonMain/resources_strings"))
    }
}
