plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.android.kotlin.multiplatform.library")
}

apply from: "$rootProject.projectDir/build-ktlint.gradle"
apply from: "$rootProject.projectDir/build-publish.gradle"
apply from: "$rootProject.projectDir/build-android-lib.gradle"
apply from: "$rootProject.projectDir/build-native-lib.gradle"

project.group = libs.versions.project.group.get()
project.version = libs.versions.project.version.get()

kotlin {
    android {
        namespace = "com.jibru.kostra"
    }

    jvm()

    createNativeTarget(delegate)

    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            dependencies {
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }

        iosArm64Main
        iosSimulatorArm64Main

        iosMain {
            dependsOn(commonMain)
            iosArm64Main.dependsOn(delegate)
            iosSimulatorArm64Main.dependsOn(delegate)
        }

        iosArm64Test
        iosSimulatorArm64Test
        iosTest {
            dependsOn(commonTest)
            iosArm64Test.dependsOn(delegate)
            iosSimulatorArm64Test.dependsOn(delegate)
        }

        jvmTest {
            dependencies {
                implementation(libs.bundles.unittest.jvm)
            }
        }

        nativeMain
    }
}
