import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    //can't be simple jvm plugin because of broken resources
    //https://youtrack.jetbrains.com/issue/KTIJ-16582/Consumer-Kotlin-JVM-library-cannot-access-a-Kotlin-Multiplatform-JVM-target-resources-in-multi-module-Gradle-project
    id("org.jetbrains.kotlin.multiplatform")
}

apply from: "$rootProject.projectDir/../build-ktlint.gradle"


kotlin {
    jvm()

    applyDefaultHierarchyTemplate()
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":shared"))
                implementation(libs.kostra.common)
                implementation(libs.kostra.compose)
            }
        }

        jvmMain {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.bundles.jetbrains.compose.app)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.bundles.unittest.jvm)
                runtimeOnly(libs.junit.platform.launcher)
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.jibru.kostra.appsample.jvm.AppKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb, TargetFormat.Exe)
            packageName = "KostraSampleApp"
            packageVersion = "1.0.0"
        }
    }
}



tasks.named("jvmTest") {
    useJUnitPlatform()
    //mockk uses logback configured via src/jvmTest/resources/logback.xml
    testLogging {
        showExceptions = true
        showStandardStreams = false
    }
}
