//
// AutoGeneratedFile
// UnicodeVersion:16.0.0
// CLDRVersion:48
//
@file:Suppress("ktlint")
package com.jibru.kostra.icu
import com.jibru.kostra.KLocale
import kotlin.Suppress
import kotlin.collections.Map
private val ordinalSpecs_01: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
  )
)}
private val ordinalSpecs_02: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 10.0, longArrayOf(1, 1, 5, 5, 7, 7, 8, 8, 9, 9, 10, 10))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 3.0, longArrayOf(2, 2, 3, 3))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 4.0, 4.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 6.0, 6.0)),
  )
)}
private val ordinalSpecs_03: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(10, true, Operand.i, true, 1.0, 8.0, longArrayOf(1, 1, 2, 2, 5, 5, 7, 7, 8, 8)),
        Constraint.Range(100, true, Operand.i, true, 20.0, 80.0, longArrayOf(20, 20, 50, 50, 70, 70, 80, 80)))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.Range(10, true, Operand.i, true, 3.0, 4.0, longArrayOf(3, 3, 4, 4)),
        Constraint.Range(1_000, true, Operand.i, true, 100.0, 900.0, longArrayOf(100, 100, 200, 200, 300, 300, 400, 400, 500, 500, 600, 600, 700, 700, 800, 800, 900, 900)))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
          Constraint.Range(10, true, Operand.i, true, 6.0, 6.0)),
        Constraint.Range(100, true, Operand.i, true, 40.0, 90.0, longArrayOf(40, 40, 60, 60, 90, 90)))),
  )
)}
private val ordinalSpecs_04: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
  )
)}
private val ordinalSpecs_05: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 2.0, 3.0, longArrayOf(2, 2, 3, 3)),
        Constraint.Range(100, false, Operand.n, true, 12.0, 13.0, longArrayOf(12, 12, 13, 13)))),
  )
)}
private val ordinalSpecs_06: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.i, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.i, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.i, true, 2.0, 6.0, longArrayOf(2, 2, 3, 3, 4, 4, 5, 5, 6, 6))),
  )
)}
private val ordinalSpecs_07: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 3.0, longArrayOf(1, 1, 3, 3))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 4.0, 4.0)),
  )
)}
private val ordinalSpecs_08: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 9.0, longArrayOf(0, 0, 7, 7, 8, 8, 9, 9))),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 3.0, 4.0, longArrayOf(3, 3, 4, 4))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 5.0, 6.0, longArrayOf(5, 5, 6, 6))),
  )
)}
private val ordinalSpecs_09: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 1.0, 1.0),
        Constraint.Range(100, false, Operand.n, true, 11.0, 11.0))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 2.0, 2.0),
        Constraint.Range(100, false, Operand.n, true, 12.0, 12.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 3.0, 3.0),
        Constraint.Range(100, false, Operand.n, true, 13.0, 13.0))),
  )
)}
private val ordinalSpecs_10: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 11.0, longArrayOf(1, 1, 11, 11))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 12.0, longArrayOf(2, 2, 12, 12))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 3.0, 13.0, longArrayOf(3, 3, 13, 13))),
  )
)}
private val ordinalSpecs_11: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 3.0, longArrayOf(2, 2, 3, 3))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 4.0, 4.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 6.0, 6.0)),
  )
)}
private val ordinalSpecs_12: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 5.0, longArrayOf(1, 1, 5, 5))),
  )
)}
private val ordinalSpecs_13: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 8.0, 800.0, longArrayOf(11, 11, 8, 8, 80, 80, 800, 800))),
  )
)}
private val ordinalSpecs_14: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.i, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
        Constraint.Range(100, true, Operand.i, true, 2.0, 80.0, longArrayOf(2, 20, 40, 40, 60, 60, 80, 80)))),
  )
)}
private val ordinalSpecs_15: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(10, true, Operand.n, true, 6.0, 6.0),
          Constraint.Range(10, true, Operand.n, true, 9.0, 9.0)),
        Constraint.And(
          Constraint.Range(10, true, Operand.n, true, 0.0, 0.0),
          Constraint.Range(0, false, Operand.n, true, 0.0, 0.0)))),
  )
)}
private val ordinalSpecs_16: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 3.0, longArrayOf(2, 2, 3, 3))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 4.0, 4.0)),
  )
)}
private val ordinalSpecs_17: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 1.0, 4.0),
        Constraint.Range(100, true, Operand.n, true, 1.0, 84.0, longArrayOf(1, 4, 21, 24, 41, 44, 61, 64, 81, 84)))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 5.0, 5.0),
        Constraint.Range(100, true, Operand.n, true, 5.0, 5.0))),
  )
)}
private val ordinalSpecs_18: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 8.0, 899.0, longArrayOf(11, 11, 8, 8, 80, 89, 800, 899))),
  )
)}
private val ordinalSpecs_19: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(100, false, Operand.i, true, 11.0, 11.0))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.i, true, 2.0, 2.0),
        Constraint.Range(100, false, Operand.i, true, 12.0, 12.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.i, true, 7.0, 8.0, longArrayOf(7, 7, 8, 8)),
        Constraint.Range(100, false, Operand.i, true, 17.0, 18.0, longArrayOf(17, 17, 18, 18)))),
  )
)}
private val ordinalSpecs_20: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 4.0)),
  )
)}
private val ordinalSpecs_21: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 9.0, longArrayOf(1, 1, 5, 5, 7, 9))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 3.0, longArrayOf(2, 2, 3, 3))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 4.0, 4.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 6.0, 6.0)),
  )
)}
private val ordinalSpecs_22: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 4.0, 4.0),
        Constraint.Range(100, false, Operand.n, true, 14.0, 14.0))),
  )
)}
private val ordinalSpecs_23: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 1.0, 2.0, longArrayOf(1, 1, 2, 2)),
        Constraint.Range(100, false, Operand.n, true, 11.0, 12.0, longArrayOf(11, 11, 12, 12)))),
  )
)}
private val ordinalSpecs_24: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.Range(10, true, Operand.n, true, 6.0, 9.0, longArrayOf(6, 6, 9, 9)),
        Constraint.Range(0, true, Operand.n, true, 10.0, 10.0))),
  )
)}
private val ordinalSpecs_25: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 3.0, 3.0),
        Constraint.Range(100, false, Operand.n, true, 13.0, 13.0))),
  )
)}
val OrdinalRuleSpecs: Map<KLocale, PluralRules> = buildMap(107) {
  put(KLocale(345_191_655_699L)/*af*/, ordinalSpecs_01)
  put(KLocale(418_414_128_120L)/*am*/, ordinalSpecs_01)
  put(KLocale(428_874_481_323L)/*an*/, ordinalSpecs_01)
  put(KLocale(470_715_894_135L)/*ar*/, ordinalSpecs_01)
  put(KLocale(481_176_247_338L)/*as*/, ordinalSpecs_02)
  put(KLocale(554_398_719_759L)/*az*/, ordinalSpecs_03)
  put(KLocale(617_160_838_977L)/*be*/, ordinalSpecs_05)
  put(KLocale(638_081_545_383L)/*bg*/, ordinalSpecs_01)
  put(KLocale(711_304_017_804L)/*bn*/, ordinalSpecs_02)
  put(KLocale(763_605_783_819L)/*bs*/, ordinalSpecs_01)
  put(KLocale(857_748_962_646L)/*ca*/, ordinalSpecs_07)
  put(KLocale(899_590_375_458L)/*ce*/, ordinalSpecs_01)
  put(KLocale(1_046_035_320_300L)/*cs*/, ordinalSpecs_01)
  put(KLocale(1_077_416_379_909L)/*cv*/, ordinalSpecs_01)
  put(KLocale(1_108_797_439_518L)/*cy*/, ordinalSpecs_08)
  put(KLocale(1_140_178_499_127L)/*da*/, ordinalSpecs_01)
  put(KLocale(1_182_019_911_939L)/*de*/, ordinalSpecs_01)
  put(KLocale(1_537_671_920_841L)/*el*/, ordinalSpecs_01)
  put(KLocale(1_558_592_627_247L)/*en*/, ordinalSpecs_09)
  put(KLocale(1_610_894_393_262L)/*es*/, ordinalSpecs_01)
  put(KLocale(1_621_354_746_465L)/*et*/, ordinalSpecs_01)
  put(KLocale(1_631_815_099_668L)/*eu*/, ordinalSpecs_01)
  put(KLocale(1_705_037_572_089L)/*fa*/, ordinalSpecs_01)
  put(KLocale(1_788_720_397_713L)/*fi*/, ordinalSpecs_01)
  put(KLocale(1_882_863_576_540L)/*fr*/, ordinalSpecs_04)
  put(KLocale(1_956_086_048_961L)/*fy*/, ordinalSpecs_01)
  put(KLocale(1_987_467_108_570L)/*ga*/, ordinalSpecs_04)
  put(KLocale(2_018_848_168_179L)/*gd*/, ordinalSpecs_10)
  put(KLocale(2_102_530_993_803L)/*gl*/, ordinalSpecs_01)
  put(KLocale(2_196_674_172_630L)/*gu*/, ordinalSpecs_11)
  put(KLocale(2_311_738_057_863L)/*he*/, ordinalSpecs_01)
  put(KLocale(2_353_579_470_675L)/*hi*/, ordinalSpecs_11)
  put(KLocale(2_447_722_649_502L)/*hr*/, ordinalSpecs_01)
  put(KLocale(2_479_103_709_111L)/*hu*/, ordinalSpecs_12)
  put(KLocale(2_520_945_121_923L)/*hy*/, ordinalSpecs_04)
  put(KLocale(2_552_326_181_532L)/*ia*/, ordinalSpecs_01)
  put(KLocale(2_583_707_241_141L)/*id*/, ordinalSpecs_01)
  put(KLocale(2_594_167_594_344L)/*ie*/, ordinalSpecs_01)
  put(KLocale(2_740_612_539_186L)/*is*/, ordinalSpecs_01)
  put(KLocale(2_751_072_892_389L)/*it*/, ordinalSpecs_13)
  put(KLocale(2_834_755_718_013L)/*ja*/, ordinalSpecs_01)
  put(KLocale(3_117_185_254_494L)/*ka*/, ordinalSpecs_14)
  put(KLocale(3_221_788_786_524L)/*kk*/, ordinalSpecs_15)
  put(KLocale(3_242_709_492_930L)/*km*/, ordinalSpecs_01)
  put(KLocale(3_253_169_846_133L)/*kn*/, ordinalSpecs_01)
  put(KLocale(3_263_630_199_336L)/*ko*/, ordinalSpecs_01)
  put(KLocale(3_347_313_024_960L)/*kw*/, ordinalSpecs_17)
  put(KLocale(3_368_233_731_366L)/*ky*/, ordinalSpecs_01)
  put(KLocale(3_546_059_735_817L)/*lo*/, ordinalSpecs_04)
  put(KLocale(3_598_361_501_832L)/*lt*/, ordinalSpecs_01)
  put(KLocale(3_619_282_208_238L)/*lv*/, ordinalSpecs_01)
  put(KLocale(3_786_647_859_486L)/*mk*/, ordinalSpecs_19)
  put(KLocale(3_797_108_212_689L)/*ml*/, ordinalSpecs_01)
  put(KLocale(3_818_028_919_095L)/*mn*/, ordinalSpecs_01)
  put(KLocale(3_828_489_272_298L)/*mo*/, ordinalSpecs_04)
  put(KLocale(3_859_870_331_907L)/*mr*/, ordinalSpecs_16)
  put(KLocale(3_870_330_685_110L)/*ms*/, ordinalSpecs_04)
  put(KLocale(3_933_092_804_328L)/*my*/, ordinalSpecs_01)
  put(KLocale(3_974_934_217_140L)/*nb*/, ordinalSpecs_01)
  put(KLocale(4_006_315_276_749L)/*ne*/, ordinalSpecs_20)
  put(KLocale(4_079_537_749_170L)/*nl*/, ordinalSpecs_01)
  put(KLocale(4_110_918_808_779L)/*no*/, ordinalSpecs_01)
  put(KLocale(4_424_729_404_869L)/*or*/, ordinalSpecs_21)
  put(KLocale(4_529_332_936_899L)/*pa*/, ordinalSpecs_01)
  put(KLocale(4_644_396_822_132L)/*pl*/, ordinalSpecs_01)
  put(KLocale(4_717_619_294_553L)/*ps*/, ordinalSpecs_01)
  put(KLocale(4_728_079_647_756L)/*pt*/, ordinalSpecs_01)
  put(KLocale(5_240_636_954_703L)/*ro*/, ordinalSpecs_04)
  put(KLocale(5_303_399_073_921L)/*ru*/, ordinalSpecs_01)
  put(KLocale(5_397_542_252_748L)/*sc*/, ordinalSpecs_13)
  put(KLocale(5_408_002_605_951L)/*sd*/, ordinalSpecs_01)
  put(KLocale(5_449_844_018_763L)/*sh*/, ordinalSpecs_01)
  put(KLocale(5_460_304_371_966L)/*si*/, ordinalSpecs_01)
  put(KLocale(5_481_225_078_372L)/*sk*/, ordinalSpecs_01)
  put(KLocale(5_491_685_431_575L)/*sl*/, ordinalSpecs_01)
  put(KLocale(5_543_987_197_590L)/*sq*/, ordinalSpecs_22)
  put(KLocale(5_554_447_550_793L)/*sr*/, ordinalSpecs_01)
  put(KLocale(5_596_288_963_605L)/*sv*/, ordinalSpecs_23)
  put(KLocale(5_606_749_316_808L)/*sw*/, ordinalSpecs_01)
  put(KLocale(5_659_051_082_823L)/*ta*/, ordinalSpecs_01)
  put(KLocale(5_700_892_495_635L)/*te*/, ordinalSpecs_01)
  put(KLocale(5_732_273_555_244L)/*th*/, ordinalSpecs_01)
  put(KLocale(5_763_654_614_853L)/*tk*/, ordinalSpecs_24)
  put(KLocale(5_774_114_968_056L)/*tl*/, ordinalSpecs_04)
  put(KLocale(5_836_877_087_274L)/*tr*/, ordinalSpecs_01)
  put(KLocale(6_046_084_151_334L)/*uk*/, ordinalSpecs_25)
  put(KLocale(6_119_306_623_755L)/*ur*/, ordinalSpecs_01)
  put(KLocale(6_202_989_449_379L)/*uz*/, ordinalSpecs_01)
  put(KLocale(6_307_592_981_409L)/*vi*/, ordinalSpecs_04)
  put(KLocale(7_426_850_774_130L)/*zh*/, ordinalSpecs_01)
  put(KLocale(7_562_835_365_769L)/*zu*/, ordinalSpecs_01)
  put(KLocale(13_200_965_742_186L)/*ast*/, ordinalSpecs_01)
  put(KLocale(15_659_148_744_891L)/*bal*/, ordinalSpecs_04)
  put(KLocale(18_797_254_705_791L)/*blo*/, ordinalSpecs_06)
  put(KLocale(35_889_471_839_493L)/*dsb*/, ordinalSpecs_01)
  put(KLocale(48_420_974_976_687L)/*fil*/, ordinalSpecs_04)
  put(KLocale(58_985_931_711_717L)/*gsw*/, ordinalSpecs_01)
  put(KLocale(66_391_861_779_441L)/*hsb*/, ordinalSpecs_01)
  put(KLocale(88_233_079_267_305L)/*kok*/, ordinalSpecs_16)
  put(KLocale(94_153_639_180_203L)/*lij*/, ordinalSpecs_18)
  put(KLocale(94_938_165_670_428L)/*lld*/, ordinalSpecs_13)
  put(KLocale(127_166_513_888_871L)/*prg*/, ordinalSpecs_01)
  put(KLocale(145_880_085_769_038L)/*scn*/, ordinalSpecs_18)
  put(KLocale(157_124_965_462_263L)/*tpi*/, ordinalSpecs_01)
  put(KLocale(164_133_402_108_273L)/*und*/, ordinalSpecs_01)
  put(KLocale(169_206_673_411_728L)/*vec*/, ordinalSpecs_13)
  put(KLocale(196_623_259_156_791L)/*yue*/, ordinalSpecs_01)
}.withDefault { PluralRules.AlwaysOther }