//
// AutoGeneratedFile
// UnicodeVersion:16.0.0
// CLDRVersion:47
//
@file:Suppress("ktlint")
package com.jibru.kostra.icu
import com.jibru.kostra.KLocale
import kotlin.Suppress
import kotlin.collections.Map
private val pluralSpecs_01: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
  )
)}
private val pluralSpecs_02: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 1.0)),
  )
)}
private val pluralSpecs_03: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
        Constraint.Range(0, true, Operand.n, true, 1.0, 1.0))),
  )
)}
private val pluralSpecs_04: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(100, true, Operand.n, true, 3.0, 10.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(100, true, Operand.n, true, 11.0, 99.0)),
  )
)}
private val pluralSpecs_05: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
  )
)}
private val pluralSpecs_06: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 1.0, 1.0),
        Constraint.Range(100, false, Operand.n, true, 11.0, 11.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 2.0, 4.0),
        Constraint.Range(100, false, Operand.n, true, 12.0, 14.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(10, true, Operand.n, true, 0.0, 0.0),
          Constraint.Range(10, true, Operand.n, true, 5.0, 9.0)),
        Constraint.Range(100, true, Operand.n, true, 11.0, 14.0))),
  )
)}
private val pluralSpecs_07: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
  )
)}
private val pluralSpecs_08: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
  )
)}
private val pluralSpecs_09: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 1.0, 1.0),
        Constraint.Range(100, false, Operand.n, true, 11.0, 91.0, longArrayOf(11, 11, 71, 71, 91, 91)))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 2.0, 2.0),
        Constraint.Range(100, false, Operand.n, true, 12.0, 92.0, longArrayOf(12, 12, 72, 72, 92, 92)))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 3.0, 9.0, longArrayOf(3, 4, 9, 9)),
        Constraint.Range(100, false, Operand.n, true, 10.0, 99.0, longArrayOf(10, 19, 70, 79, 90, 99)))),
    Rule(category = PluralCategory.Many, constraint = Constraint.And(
        Constraint.Range(0, false, Operand.n, true, 0.0, 0.0),
        Constraint.Range(1_000_000, true, Operand.n, true, 0.0, 0.0))),
  )
)}
private val pluralSpecs_10: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 1.0, 1.0)),
          Constraint.Range(100, false, Operand.i, true, 11.0, 11.0)),
        Constraint.And(
          Constraint.Range(10, true, Operand.f, true, 1.0, 1.0),
          Constraint.Range(100, false, Operand.f, true, 11.0, 11.0)))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 2.0, 4.0)),
          Constraint.Range(100, false, Operand.i, true, 12.0, 14.0)),
        Constraint.And(
          Constraint.Range(10, true, Operand.f, true, 2.0, 4.0),
          Constraint.Range(100, false, Operand.f, true, 12.0, 14.0)))),
  )
)}
private val pluralSpecs_11: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.e, true, 0.0, 0.0),
              Constraint.Range(0, false, Operand.i, true, 0.0, 0.0)),
            Constraint.Range(1_000_000, true, Operand.i, true, 0.0, 0.0)),
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0)),
        Constraint.Range(0, false, Operand.e, true, 0.0, 5.0))),
  )
)}
private val pluralSpecs_12: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(0, true, Operand.i, true, 1.0, 3.0, longArrayOf(1, 1, 2, 2, 3, 3))),
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, false, Operand.i, true, 4.0, 9.0, longArrayOf(4, 4, 6, 6, 9, 9)))),
        Constraint.And(
          Constraint.Range(0, false, Operand.v, true, 0.0, 0.0),
          Constraint.Range(10, false, Operand.f, true, 4.0, 9.0, longArrayOf(4, 4, 6, 6, 9, 9))))),
  )
)}
private val pluralSpecs_13: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 2.0, 4.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, false, Operand.v, true, 0.0, 0.0)),
  )
)}
private val pluralSpecs_14: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 3.0, 3.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 6.0, 6.0)),
  )
)}
private val pluralSpecs_15: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 1.0, 1.0),
        Constraint.And(
          Constraint.Range(0, false, Operand.t, true, 0.0, 0.0),
          Constraint.Range(0, true, Operand.i, true, 0.0, 1.0, longArrayOf(0, 0, 1, 1))))),
  )
)}
private val pluralSpecs_16: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 1.0, 1.0)),
        Constraint.Range(100, true, Operand.f, true, 1.0, 1.0))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Or(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 2.0, 2.0)),
        Constraint.Range(100, true, Operand.f, true, 2.0, 2.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 3.0, 4.0)),
        Constraint.Range(100, true, Operand.f, true, 3.0, 4.0))),
  )
)}
private val pluralSpecs_17: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.e, true, 0.0, 0.0),
              Constraint.Range(0, false, Operand.i, true, 0.0, 0.0)),
            Constraint.Range(1_000_000, true, Operand.i, true, 0.0, 0.0)),
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0)),
        Constraint.Range(0, false, Operand.e, true, 0.0, 5.0))),
  )
)}
private val pluralSpecs_18: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.i, true, 0.0, 1.0, longArrayOf(0, 0, 1, 1))),
  )
)}
private val pluralSpecs_19: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.i, true, 0.0, 1.0, longArrayOf(0, 0, 1, 1))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.e, true, 0.0, 0.0),
              Constraint.Range(0, false, Operand.i, true, 0.0, 0.0)),
            Constraint.Range(1_000_000, true, Operand.i, true, 0.0, 0.0)),
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0)),
        Constraint.Range(0, false, Operand.e, true, 0.0, 5.0))),
  )
)}
private val pluralSpecs_20: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 3.0, 6.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, true, Operand.n, true, 7.0, 10.0)),
  )
)}
private val pluralSpecs_21: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 11.0, longArrayOf(1, 1, 11, 11))),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 12.0, longArrayOf(2, 2, 12, 12))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 3.0, 19.0, longArrayOf(3, 10, 13, 19))),
  )
)}
private val pluralSpecs_22: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
        Constraint.Range(10, true, Operand.i, true, 1.0, 1.0))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
        Constraint.Range(10, true, Operand.i, true, 2.0, 2.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
        Constraint.Range(100, true, Operand.i, true, 0.0, 80.0, longArrayOf(0, 0, 20, 20, 40, 40, 60, 60, 80, 80)))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, false, Operand.v, true, 0.0, 0.0)),
  )
)}
private val pluralSpecs_23: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.And(
          Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0)),
        Constraint.And(
          Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
          Constraint.Range(0, false, Operand.v, true, 0.0, 0.0)))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 2.0, 2.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
  )
)}
private val pluralSpecs_24: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.Range(0, true, Operand.t, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 1.0, 1.0)),
          Constraint.Range(100, false, Operand.i, true, 11.0, 11.0)),
        Constraint.And(
          Constraint.Range(10, true, Operand.t, true, 1.0, 1.0),
          Constraint.Range(100, false, Operand.t, true, 11.0, 11.0)))),
  )
)}
private val pluralSpecs_25: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
  )
)}
private val pluralSpecs_26: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(100, true, Operand.n, true, 2.0, 82.0, longArrayOf(2, 2, 22, 22, 42, 42, 62, 62, 82, 82)),
          Constraint.And(
            Constraint.Range(1_000, true, Operand.n, true, 0.0, 0.0),
            Constraint.Range(100_000, true, Operand.n, true, 1_000.0, 80_000.0, longArrayOf(1000, 20000, 40000, 40000, 60000, 60000, 80000, 80000)))),
        Constraint.And(
          Constraint.Range(0, false, Operand.n, true, 0.0, 0.0),
          Constraint.Range(1_000_000, true, Operand.n, true, 100_000.0, 100_000.0)))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(100, true, Operand.n, true, 3.0, 83.0, longArrayOf(3, 3, 23, 23, 43, 43, 63, 63, 83, 83))),
    Rule(category = PluralCategory.Many, constraint = Constraint.And(
        Constraint.Range(0, false, Operand.n, true, 1.0, 1.0),
        Constraint.Range(100, true, Operand.n, true, 1.0, 81.0, longArrayOf(1, 1, 21, 21, 41, 41, 61, 61, 81, 81)))),
  )
)}
private val pluralSpecs_27: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 0.0, 1.0, longArrayOf(0, 0, 1, 1)),
        Constraint.Range(0, false, Operand.n, true, 0.0, 0.0))),
  )
)}
private val pluralSpecs_28: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 1.0, 1.0),
        Constraint.Range(100, false, Operand.n, true, 11.0, 19.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.Range(10, true, Operand.n, true, 2.0, 9.0),
        Constraint.Range(100, false, Operand.n, true, 11.0, 19.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(0, false, Operand.f, true, 0.0, 0.0)),
  )
)}
private val pluralSpecs_29: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.Zero, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(10, true, Operand.n, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.n, true, 11.0, 19.0)),
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 2.0, 2.0),
          Constraint.Range(100, true, Operand.f, true, 11.0, 19.0)))),
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.And(
            Constraint.Range(10, true, Operand.n, true, 1.0, 1.0),
            Constraint.Range(100, false, Operand.n, true, 11.0, 11.0)),
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.v, true, 2.0, 2.0),
              Constraint.Range(10, true, Operand.f, true, 1.0, 1.0)),
            Constraint.Range(100, false, Operand.f, true, 11.0, 11.0))),
        Constraint.And(
          Constraint.Range(0, false, Operand.v, true, 2.0, 2.0),
          Constraint.Range(10, true, Operand.f, true, 1.0, 1.0)))),
  )
)}
private val pluralSpecs_30: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 1.0, 1.0)),
          Constraint.Range(100, false, Operand.i, true, 11.0, 11.0)),
        Constraint.And(
          Constraint.Range(10, true, Operand.f, true, 1.0, 1.0),
          Constraint.Range(100, false, Operand.f, true, 11.0, 11.0)))),
  )
)}
private val pluralSpecs_31: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.Range(0, false, Operand.v, true, 0.0, 0.0),
          Constraint.Range(0, true, Operand.n, true, 0.0, 0.0)),
        Constraint.And(
          Constraint.Range(0, false, Operand.n, true, 1.0, 1.0),
          Constraint.Range(100, true, Operand.n, true, 1.0, 19.0)))),
  )
)}
private val pluralSpecs_32: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.n, true, 1.0, 1.0)),
    Rule(category = PluralCategory.Two, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 2.0)),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 0.0, 0.0),
        Constraint.Range(100, true, Operand.n, true, 3.0, 10.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Range(100, true, Operand.n, true, 11.0, 19.0)),
  )
)}
private val pluralSpecs_33: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.i, true, 1.0, 1.0),
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(10, true, Operand.i, true, 2.0, 4.0)),
        Constraint.Range(100, false, Operand.i, true, 12.0, 14.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
              Constraint.Range(0, false, Operand.i, true, 1.0, 1.0)),
            Constraint.Range(10, true, Operand.i, true, 0.0, 1.0)),
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 5.0, 9.0))),
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 12.0, 14.0)))),
  )
)}
private val pluralSpecs_34: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Range(0, true, Operand.i, true, 0.0, 1.0)),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.And(
          Constraint.And(
            Constraint.And(
              Constraint.Range(0, true, Operand.e, true, 0.0, 0.0),
              Constraint.Range(0, false, Operand.i, true, 0.0, 0.0)),
            Constraint.Range(1_000_000, true, Operand.i, true, 0.0, 0.0)),
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0)),
        Constraint.Range(0, false, Operand.e, true, 0.0, 5.0))),
  )
)}
private val pluralSpecs_35: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(10, true, Operand.i, true, 1.0, 1.0)),
        Constraint.Range(100, false, Operand.i, true, 11.0, 11.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.And(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(10, true, Operand.i, true, 2.0, 4.0)),
        Constraint.Range(100, false, Operand.i, true, 12.0, 14.0))),
    Rule(category = PluralCategory.Many, constraint = Constraint.Or(
        Constraint.Or(
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 0.0, 0.0)),
          Constraint.And(
            Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
            Constraint.Range(10, true, Operand.i, true, 5.0, 9.0))),
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 11.0, 14.0)))),
  )
)}
private val pluralSpecs_36: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
        Constraint.Range(0, true, Operand.n, true, 1.0, 1.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Range(0, true, Operand.n, true, 2.0, 10.0)),
  )
)}
private val pluralSpecs_37: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 0.0, 1.0, longArrayOf(0, 0, 1, 1)),
        Constraint.And(
          Constraint.Range(0, true, Operand.i, true, 0.0, 0.0),
          Constraint.Range(0, true, Operand.f, true, 1.0, 1.0)))),
  )
)}
private val pluralSpecs_38: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
        Constraint.Range(100, true, Operand.i, true, 1.0, 1.0))),
    Rule(category = PluralCategory.Two, constraint = Constraint.And(
        Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
        Constraint.Range(100, true, Operand.i, true, 2.0, 2.0))),
    Rule(category = PluralCategory.Few, constraint = Constraint.Or(
        Constraint.And(
          Constraint.Range(0, true, Operand.v, true, 0.0, 0.0),
          Constraint.Range(100, true, Operand.i, true, 3.0, 4.0)),
        Constraint.Range(0, false, Operand.v, true, 0.0, 0.0))),
  )
)}
private val pluralSpecs_39: PluralRules by lazy(LazyThreadSafetyMode.NONE) { PluralRules(
  rules = listOf(
    Rule(category = PluralCategory.One, constraint = Constraint.Or(
        Constraint.Range(0, true, Operand.n, true, 0.0, 1.0),
        Constraint.Range(0, true, Operand.n, true, 11.0, 99.0))),
  )
)}
val PluralRuleSpecs: Map<KLocale, PluralRules> = buildMap(218) {
  put(KLocale(345_191_655_699L)/*af*/, pluralSpecs_01)
  put(KLocale(397_493_421_714L)/*ak*/, pluralSpecs_02)
  put(KLocale(418_414_128_120L)/*am*/, pluralSpecs_03)
  put(KLocale(428_874_481_323L)/*an*/, pluralSpecs_01)
  put(KLocale(470_715_894_135L)/*ar*/, pluralSpecs_04)
  put(KLocale(481_176_247_338L)/*as*/, pluralSpecs_03)
  put(KLocale(554_398_719_759L)/*az*/, pluralSpecs_01)
  put(KLocale(617_160_838_977L)/*be*/, pluralSpecs_06)
  put(KLocale(638_081_545_383L)/*bg*/, pluralSpecs_01)
  put(KLocale(700_843_664_601L)/*bm*/, pluralSpecs_08)
  put(KLocale(711_304_017_804L)/*bn*/, pluralSpecs_03)
  put(KLocale(721_764_371_007L)/*bo*/, pluralSpecs_08)
  put(KLocale(753_145_430_616L)/*br*/, pluralSpecs_09)
  put(KLocale(763_605_783_819L)/*bs*/, pluralSpecs_10)
  put(KLocale(857_748_962_646L)/*ca*/, pluralSpecs_11)
  put(KLocale(899_590_375_458L)/*ce*/, pluralSpecs_01)
  put(KLocale(1_046_035_320_300L)/*cs*/, pluralSpecs_13)
  put(KLocale(1_108_797_439_518L)/*cy*/, pluralSpecs_14)
  put(KLocale(1_140_178_499_127L)/*da*/, pluralSpecs_15)
  put(KLocale(1_182_019_911_939L)/*de*/, pluralSpecs_05)
  put(KLocale(1_359_845_916_390L)/*dv*/, pluralSpecs_01)
  put(KLocale(1_401_687_329_202L)/*dz*/, pluralSpecs_08)
  put(KLocale(1_464_449_448_420L)/*ee*/, pluralSpecs_01)
  put(KLocale(1_537_671_920_841L)/*el*/, pluralSpecs_01)
  put(KLocale(1_558_592_627_247L)/*en*/, pluralSpecs_05)
  put(KLocale(1_569_052_980_450L)/*eo*/, pluralSpecs_01)
  put(KLocale(1_610_894_393_262L)/*es*/, pluralSpecs_17)
  put(KLocale(1_621_354_746_465L)/*et*/, pluralSpecs_05)
  put(KLocale(1_631_815_099_668L)/*eu*/, pluralSpecs_01)
  put(KLocale(1_705_037_572_089L)/*fa*/, pluralSpecs_03)
  put(KLocale(1_757_339_338_104L)/*ff*/, pluralSpecs_18)
  put(KLocale(1_788_720_397_713L)/*fi*/, pluralSpecs_05)
  put(KLocale(1_851_482_516_931L)/*fo*/, pluralSpecs_01)
  put(KLocale(1_882_863_576_540L)/*fr*/, pluralSpecs_19)
  put(KLocale(1_956_086_048_961L)/*fy*/, pluralSpecs_05)
  put(KLocale(1_987_467_108_570L)/*ga*/, pluralSpecs_20)
  put(KLocale(2_018_848_168_179L)/*gd*/, pluralSpecs_21)
  put(KLocale(2_102_530_993_803L)/*gl*/, pluralSpecs_05)
  put(KLocale(2_196_674_172_630L)/*gu*/, pluralSpecs_03)
  put(KLocale(2_207_134_525_833L)/*gv*/, pluralSpecs_22)
  put(KLocale(2_269_896_645_051L)/*ha*/, pluralSpecs_01)
  put(KLocale(2_311_738_057_863L)/*he*/, pluralSpecs_23)
  put(KLocale(2_353_579_470_675L)/*hi*/, pluralSpecs_03)
  put(KLocale(2_447_722_649_502L)/*hr*/, pluralSpecs_10)
  put(KLocale(2_479_103_709_111L)/*hu*/, pluralSpecs_01)
  put(KLocale(2_520_945_121_923L)/*hy*/, pluralSpecs_18)
  put(KLocale(2_552_326_181_532L)/*ia*/, pluralSpecs_05)
  put(KLocale(2_583_707_241_141L)/*id*/, pluralSpecs_08)
  put(KLocale(2_615_088_300_750L)/*ig*/, pluralSpecs_08)
  put(KLocale(2_636_009_007_156L)/*ii*/, pluralSpecs_08)
  put(KLocale(2_698_771_126_374L)/*io*/, pluralSpecs_05)
  put(KLocale(2_740_612_539_186L)/*is*/, pluralSpecs_24)
  put(KLocale(2_751_072_892_389L)/*it*/, pluralSpecs_11)
  put(KLocale(2_761_533_245_592L)/*iu*/, pluralSpecs_25)
  put(KLocale(2_834_755_718_013L)/*ja*/, pluralSpecs_08)
  put(KLocale(3_054_423_135_276L)/*jv*/, pluralSpecs_08)
  put(KLocale(3_064_883_488_479L)/*jw*/, pluralSpecs_08)
  put(KLocale(3_117_185_254_494L)/*ka*/, pluralSpecs_01)
  put(KLocale(3_221_788_786_524L)/*kk*/, pluralSpecs_01)
  put(KLocale(3_232_249_139_727L)/*kl*/, pluralSpecs_01)
  put(KLocale(3_242_709_492_930L)/*km*/, pluralSpecs_08)
  put(KLocale(3_253_169_846_133L)/*kn*/, pluralSpecs_03)
  put(KLocale(3_263_630_199_336L)/*ko*/, pluralSpecs_08)
  put(KLocale(3_305_471_612_148L)/*ks*/, pluralSpecs_01)
  put(KLocale(3_326_392_318_554L)/*ku*/, pluralSpecs_01)
  put(KLocale(3_347_313_024_960L)/*kw*/, pluralSpecs_26)
  put(KLocale(3_368_233_731_366L)/*ky*/, pluralSpecs_01)
  put(KLocale(3_410_075_144_178L)/*lb*/, pluralSpecs_01)
  put(KLocale(3_462_376_910_193L)/*lg*/, pluralSpecs_01)
  put(KLocale(3_535_599_382_614L)/*ln*/, pluralSpecs_02)
  put(KLocale(3_546_059_735_817L)/*lo*/, pluralSpecs_08)
  put(KLocale(3_598_361_501_832L)/*lt*/, pluralSpecs_28)
  put(KLocale(3_619_282_208_238L)/*lv*/, pluralSpecs_29)
  put(KLocale(3_744_806_446_674L)/*mg*/, pluralSpecs_02)
  put(KLocale(3_786_647_859_486L)/*mk*/, pluralSpecs_30)
  put(KLocale(3_797_108_212_689L)/*ml*/, pluralSpecs_01)
  put(KLocale(3_818_028_919_095L)/*mn*/, pluralSpecs_01)
  put(KLocale(3_828_489_272_298L)/*mo*/, pluralSpecs_31)
  put(KLocale(3_859_870_331_907L)/*mr*/, pluralSpecs_01)
  put(KLocale(3_870_330_685_110L)/*ms*/, pluralSpecs_08)
  put(KLocale(3_880_791_038_313L)/*mt*/, pluralSpecs_32)
  put(KLocale(3_933_092_804_328L)/*my*/, pluralSpecs_08)
  put(KLocale(3_974_934_217_140L)/*nb*/, pluralSpecs_01)
  put(KLocale(3_995_854_923_546L)/*nd*/, pluralSpecs_01)
  put(KLocale(4_006_315_276_749L)/*ne*/, pluralSpecs_01)
  put(KLocale(4_079_537_749_170L)/*nl*/, pluralSpecs_05)
  put(KLocale(4_100_458_455_576L)/*nn*/, pluralSpecs_01)
  put(KLocale(4_110_918_808_779L)/*no*/, pluralSpecs_01)
  put(KLocale(4_142_299_868_388L)/*nr*/, pluralSpecs_01)
  put(KLocale(4_215_522_340_809L)/*ny*/, pluralSpecs_01)
  put(KLocale(4_372_427_638_854L)/*om*/, pluralSpecs_01)
  put(KLocale(4_424_729_404_869L)/*or*/, pluralSpecs_01)
  put(KLocale(4_435_189_758_072L)/*os*/, pluralSpecs_01)
  put(KLocale(4_529_332_936_899L)/*pa*/, pluralSpecs_02)
  put(KLocale(4_644_396_822_132L)/*pl*/, pluralSpecs_33)
  put(KLocale(4_717_619_294_553L)/*ps*/, pluralSpecs_01)
  put(KLocale(4_728_079_647_756L)/*pt*/, pluralSpecs_34)
  put(KLocale(5_219_716_248_297L)/*rm*/, pluralSpecs_01)
  put(KLocale(5_240_636_954_703L)/*ro*/, pluralSpecs_31)
  put(KLocale(5_303_399_073_921L)/*ru*/, pluralSpecs_35)
  put(KLocale(5_397_542_252_748L)/*sc*/, pluralSpecs_05)
  put(KLocale(5_408_002_605_951L)/*sd*/, pluralSpecs_01)
  put(KLocale(5_418_462_959_154L)/*se*/, pluralSpecs_25)
  put(KLocale(5_439_383_665_560L)/*sg*/, pluralSpecs_08)
  put(KLocale(5_449_844_018_763L)/*sh*/, pluralSpecs_10)
  put(KLocale(5_460_304_371_966L)/*si*/, pluralSpecs_37)
  put(KLocale(5_481_225_078_372L)/*sk*/, pluralSpecs_13)
  put(KLocale(5_491_685_431_575L)/*sl*/, pluralSpecs_38)
  put(KLocale(5_512_606_137_981L)/*sn*/, pluralSpecs_01)
  put(KLocale(5_523_066_491_184L)/*so*/, pluralSpecs_01)
  put(KLocale(5_543_987_197_590L)/*sq*/, pluralSpecs_01)
  put(KLocale(5_554_447_550_793L)/*sr*/, pluralSpecs_10)
  put(KLocale(5_564_907_903_996L)/*ss*/, pluralSpecs_01)
  put(KLocale(5_575_368_257_199L)/*st*/, pluralSpecs_01)
  put(KLocale(5_585_828_610_402L)/*su*/, pluralSpecs_08)
  put(KLocale(5_596_288_963_605L)/*sv*/, pluralSpecs_05)
  put(KLocale(5_606_749_316_808L)/*sw*/, pluralSpecs_05)
  put(KLocale(5_659_051_082_823L)/*ta*/, pluralSpecs_01)
  put(KLocale(5_700_892_495_635L)/*te*/, pluralSpecs_01)
  put(KLocale(5_732_273_555_244L)/*th*/, pluralSpecs_08)
  put(KLocale(5_742_733_908_447L)/*ti*/, pluralSpecs_02)
  put(KLocale(5_763_654_614_853L)/*tk*/, pluralSpecs_01)
  put(KLocale(5_774_114_968_056L)/*tl*/, pluralSpecs_12)
  put(KLocale(5_795_035_674_462L)/*tn*/, pluralSpecs_01)
  put(KLocale(5_805_496_027_665L)/*to*/, pluralSpecs_08)
  put(KLocale(5_836_877_087_274L)/*tr*/, pluralSpecs_01)
  put(KLocale(5_847_337_440_477L)/*ts*/, pluralSpecs_01)
  put(KLocale(6_004_242_738_522L)/*ug*/, pluralSpecs_01)
  put(KLocale(6_046_084_151_334L)/*uk*/, pluralSpecs_35)
  put(KLocale(6_119_306_623_755L)/*ur*/, pluralSpecs_05)
  put(KLocale(6_202_989_449_379L)/*uz*/, pluralSpecs_01)
  put(KLocale(6_265_751_568_597L)/*ve*/, pluralSpecs_01)
  put(KLocale(6_307_592_981_409L)/*vi*/, pluralSpecs_08)
  put(KLocale(6_370_355_100_627L)/*vo*/, pluralSpecs_01)
  put(KLocale(6_506_339_692_266L)/*wa*/, pluralSpecs_02)
  put(KLocale(6_652_784_637_108L)/*wo*/, pluralSpecs_08)
  put(KLocale(6_861_991_701_168L)/*xh*/, pluralSpecs_01)
  put(KLocale(7_154_881_590_852L)/*yi*/, pluralSpecs_05)
  put(KLocale(7_217_643_710_070L)/*yo*/, pluralSpecs_08)
  put(KLocale(7_426_850_774_130L)/*zh*/, pluralSpecs_08)
  put(KLocale(7_562_835_365_769L)/*zu*/, pluralSpecs_03)
  put(KLocale(12_908_075_852_502L)/*ars*/, pluralSpecs_04)
  put(KLocale(13_002_219_031_329L)/*asa*/, pluralSpecs_01)
  put(KLocale(13_200_965_742_186L)/*ast*/, pluralSpecs_05)
  put(KLocale(15_659_148_744_891L)/*bal*/, pluralSpecs_01)
  put(KLocale(16_799_327_244_018L)/*bem*/, pluralSpecs_01)
  put(KLocale(16_935_311_835_657L)/*bez*/, pluralSpecs_01)
  put(KLocale(17_667_536_559_867L)/*bho*/, pluralSpecs_02)
  put(KLocale(18_797_254_705_791L)/*blo*/, pluralSpecs_07)
  put(KLocale(20_585_975_103_504L)/*brx*/, pluralSpecs_01)
  put(KLocale(24_309_860_843_772L)/*ceb*/, pluralSpecs_12)
  put(KLocale(24_927_021_682_749L)/*cgg*/, pluralSpecs_01)
  put(KLocale(25_324_515_104_463L)/*chr*/, pluralSpecs_01)
  put(KLocale(26_004_438_062_658L)/*ckb*/, pluralSpecs_01)
  put(KLocale(28_483_541_771_769L)/*csw*/, pluralSpecs_02)
  put(KLocale(34_832_976_165_990L)/*doi*/, pluralSpecs_03)
  put(KLocale(35_889_471_839_493L)/*dsb*/, pluralSpecs_16)
  put(KLocale(48_420_974_976_687L)/*fil*/, pluralSpecs_12)
  put(KLocale(51_872_891_533_677L)/*fur*/, pluralSpecs_01)
  put(KLocale(58_985_931_711_717L)/*gsw*/, pluralSpecs_01)
  put(KLocale(59_550_790_784_679L)/*guw*/, pluralSpecs_02)
  put(KLocale(61_527_797_540_046L)/*haw*/, pluralSpecs_01)
  put(KLocale(65_063_396_922_660L)/*hnj*/, pluralSpecs_08)
  put(KLocale(66_391_861_779_441L)/*hsb*/, pluralSpecs_16)
  put(KLocale(76_977_739_220_877L)/*jbo*/, pluralSpecs_08)
  put(KLocale(78_389_886_903_282L)/*jgo*/, pluralSpecs_01)
  put(KLocale(79_958_939_883_732L)/*jmc*/, pluralSpecs_01)
  put(KLocale(84_184_922_577_744L)/*kab*/, pluralSpecs_18)
  put(KLocale(84_268_605_403_368L)/*kaj*/, pluralSpecs_01)
  put(KLocale(84_802_083_416_721L)/*kcg*/, pluralSpecs_01)
  put(KLocale(85_063_592_246_796L)/*kde*/, pluralSpecs_08)
  put(KLocale(85_304_180_370_465L)/*kea*/, pluralSpecs_08)
  put(KLocale(87_092_900_768_178L)/*kkj*/, pluralSpecs_01)
  put(KLocale(89_268_654_234_402L)/*ksb*/, pluralSpecs_01)
  put(KLocale(89_331_416_353_620L)/*ksh*/, pluralSpecs_07)
  put(KLocale(91_862_821_828_746L)/*lag*/, pluralSpecs_27)
  put(KLocale(94_153_639_180_203L)/*lij*/, pluralSpecs_05)
  put(KLocale(94_823_101_785_195L)/*lkt*/, pluralSpecs_08)
  put(KLocale(94_938_165_670_428L)/*lld*/, pluralSpecs_11)
  put(KLocale(99_613_943_552_169L)/*mas*/, pluralSpecs_01)
  put(KLocale(101_266_679_358_243L)/*mgo*/, pluralSpecs_01)
  put(KLocale(107_124_477_151_923L)/*nah*/, pluralSpecs_01)
  put(KLocale(107_218_620_330_750L)/*naq*/, pluralSpecs_25)
  put(KLocale(110_796_061_126_176L)/*nnh*/, pluralSpecs_01)
  put(KLocale(111_716_572_208_040L)/*nqo*/, pluralSpecs_08)
  put(KLocale(112_281_431_281_002L)/*nso*/, pluralSpecs_02)
  put(KLocale(113_965_548_146_685L)/*nyn*/, pluralSpecs_01)
  put(KLocale(119_760_583_821_147L)/*osa*/, pluralSpecs_08)
  put(KLocale(122_459_354_947_521L)/*pap*/, pluralSpecs_01)
  put(KLocale(122_992_832_960_874L)/*pcm*/, pluralSpecs_03)
  put(KLocale(127_166_513_888_871L)/*prg*/, pluralSpecs_29)
  put(KLocale(141_559_959_896_199L)/*rof*/, pluralSpecs_01)
  put(KLocale(143_871_697_954_062L)/*rwk*/, pluralSpecs_01)
  put(KLocale(145_252_464_576_858L)/*sah*/, pluralSpecs_08)
  put(KLocale(145_346_607_755_685L)/*saq*/, pluralSpecs_01)
  put(KLocale(145_377_988_815_294L)/*sat*/, pluralSpecs_25)
  put(KLocale(145_880_085_769_038L)/*scn*/, pluralSpecs_11)
  put(KLocale(146_099_753_186_301L)/*sdh*/, pluralSpecs_01)
  put(KLocale(146_382_182_722_782L)/*seh*/, pluralSpecs_01)
  put(KLocale(146_497_246_608_015L)/*ses*/, pluralSpecs_08)
  put(KLocale(147_239_931_685_428L)/*shi*/, pluralSpecs_36)
  put(KLocale(148_568_396_542_209L)/*sma*/, pluralSpecs_25)
  put(KLocale(148_652_079_367_833L)/*smi*/, pluralSpecs_25)
  put(KLocale(148_662_539_721_036L)/*smj*/, pluralSpecs_25)
  put(KLocale(148_704_381_133_848L)/*smn*/, pluralSpecs_25)
  put(KLocale(148_756_682_899_863L)/*sms*/, pluralSpecs_25)
  put(KLocale(150_514_022_237_967L)/*ssy*/, pluralSpecs_01)
  put(KLocale(152_135_376_984_432L)/*syr*/, pluralSpecs_01)
  put(KLocale(154_081_002_680_190L)/*teo*/, pluralSpecs_01)
  put(KLocale(155_127_038_000_490L)/*tig*/, pluralSpecs_01)
  put(KLocale(157_124_965_462_263L)/*tpi*/, pluralSpecs_08)
  put(KLocale(159_991_102_239_885L)/*tzm*/, pluralSpecs_39)
  put(KLocale(164_133_402_108_273L)/*und*/, pluralSpecs_08)
  put(KLocale(169_206_673_411_728L)/*vec*/, pluralSpecs_11)
  put(KLocale(173_840_609_880_657L)/*vun*/, pluralSpecs_01)
  put(KLocale(175_723_473_457_197L)/*wae*/, pluralSpecs_01)
  put(KLocale(187_324_005_159_324L)/*xog*/, pluralSpecs_01)
  put(KLocale(196_623_259_156_791L)/*yue*/, pluralSpecs_08)
}.withDefault { PluralRules.AlwaysOther }