name: Dyno Maven Publish

on: workflow_dispatch

jobs:
  dynoMavenPublish:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish Snapshot to MavenDyno
      run: ./gradlew publishAllPublicationsToDynoRepository --parallel --build-cache
