name: Kostra CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  kostraCI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          #keep caching only for github hosts, as the cache is being there
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for sample/gradlew
        run: chmod +x sample/gradlew
      - name: KtlintCheck
        run: sample/gradlew ktlintCheck
      - name: Build & Test
        run: ./gradlew test build
      - name: Build & Test
        run: sample/gradlew clean test build
